variable "vmssName" {}
variable "resourceGroupName" {}
variable "location" {}
variable "additionalTags" {}
variable "vmssSku" {}
variable "vmssInstanceCount" {}
variable "image" {}
variable "disk" {}
variable "subnet_id" {}
variable "public_key" {}
variable "backend_address_pool_id" {}
