enabled: true
# automerge:
#   delete_branch: true
#   enabled: true
#       # prod:
#       #   tags: [prod]

cost_estimation:
  currency: AUD
  enabled: true
  provider: infracost

when_modified:
  autoplan: true
dirs:
  azure/**:
    create_and_select_workspace: false
    tags: [azure]
    workspaces:
      dev:
        tags: [dev]
workflows:
  - tag_query: azure dev
    plan:
      - type: init
      - type: plan
        extra_args: ["-var-file=dev.tfvars"]
      - type: env
        name: CKV_SKIP_CHECK
        cmd: ['LOW']
      - type: run
        cmd: ['checkov-wrapper']
        capture_output: true
          
  # - tag_query: azure prod
  #   plan:
  #     - type: init
  #     - type: plan
  #       extra_args: ["-var-file=prod.tfvars"]
