---
automerge:
  delete_branch: true
  enabled: true
      # prod:
      #   tags: [prod]
cost_estimation:
  currency: AUD
  enabled: true
  provider: infracost
dirs:
  azure:
    create_and_select_workspace: false
    tags: [azure]
    workspaces:
      dev:
        tags: [dev]
enabled: true
when_modified:
  autoplan: false
workflows:
  - tag_query: azure dev
    plan:
      - type: init
      - type: plan
        extra_args: ["-var-file=dev.tfvars"]
    
  # - tag_query: azure prod
  #   plan:
  #     - type: init
  #     - type: plan
  #       extra_args: ["-var-file=prod.tfvars"]