enabled: true
automerge:
  enabled: true
  delete_branch: true

when_modified:
  autoplan: true
dirs:
  azure:
    create_and_select_workspace: false
    tags: [azure]
    workspaces:
      dev:
        tags: [dev]
      prod:
        tags: [prod]
workflows:
  - tag_query: azure dev
    plan:
      - type: init
      - type: plan
        extra_args: ["-var-file=dev.tfvars"]
  - tag_query: azure prod
    plan:
      - type: init
      - type: plan
        extra_args: ["-var-file=prod.tfvars"]